Repository i-dot-ai/consultation-analyser, pull requests merged in 2024-06, with the labels that each got.

#280 EN-28 secrets tag migration
  Makefile
  infrastructure/postgres.tf
  infrastructure/secrets.tf
Labels: infrastructure

#296 Bugfix/Only one user could be added to a consultation at a time
  consultation_analyser/consultations/views/questions.py
  consultation_analyser/support_console/views/consultations_users.py
  tests/integration/test_managing_consultation_users_via_support.py
Labels: bug

#297 Bugfix/Do not send unhandled errors to Sentry
  consultation_analyser/settings/production.py
Labels: bug

#295 Feature/Display version tag in deployed environments
  consultation_analyser/consultations/jinja2/base.html
  consultation_analyser/context_processors.py
  consultation_analyser/settings/base.py
  tests/integration/test_git_version.py
Labels: infrastructure

#302 Refactor/Give names to the datatypes in the BERTopic pipeline
  consultation_analyser/pipeline/backends/bertopic.py
Labels: processing pipeline
